version: '1'
environments:
  europe:
    - OS_REGION_NAME=EUR
  USEast:
    - OS_REGION_NAME=US-EAST

services:
  terraform:
    abstract: true
    commands:
      init: [terraform init -backend-config=$HOME/.wayoos/backend-variables.tf]
      up: [terraform apply]
      down: [terraform destroy -force]
  global:
    parent: terraform
    path: global
  bastion:
    parent: terraform
    path: mgmt/services/bastion
    environment:
      - OS_REGION_NAME2=EURCUSTOM
    commands:
      ssh: [./script-ssh-connect.sh]
  up:
    commands:
      all:
        - europe global up
        - USEast global up
        - bastion up
  down:
    commands:
      all: [bastion down]
