version: '1'
environment:
  - GLOBAL=value

services:
  root:
    abstract: true
    commands:
      clean: [ls]
      init: [terraform init]
  terraform:
    abstract: true
    parent: root
    environment:
      - TEST=Value
    variables:
      backend-variables:
        file: .terraform/backend-variables.tf
        environment:
          - "project = \"wayoos-terraform-admin\""
          - "bucket = \"${branch.first}.tfstate.wayoos.info\""
    commands:
      init:
        - terraform init
      up: [terraform apply]
      down: [terraform destroy -force]
  global:
    parent: terraform
    path: global
  bastion:
    parent: terraform
    path: mgmt/services/bastion
    variables:
      backend-variables:
        file: .terraform/backend-variables.tf
        environment:
          - "bucket = \"${branch.first}.bobo.tfstate.wayoos.info\""
          - "test = \"value\""
    environment:
      - OS_REGION_NAME2=EURCUSTOM
    commands:
      ssh: [./script-ssh-connect.sh]
      test:
        - global down ${arg.0}
  up:
    command:
      - _global up
      - _bastion up
      - _bastion ssh
      - _bastion test
  down:
    commands:
      all: [bastion down]
