version: '1'
environment:
  - GLOBAL=value
environments:
  europe:
    - OS_REGION_NAME=EUR
  USEast:
    - OS_REGION_NAME=US-EAST

services:
  terraform:
    abstract: true
    environment:
      - TEST=Value
    variables:
      backend-variables:
        file: .terraform/backend-variables.tf
        environment:
          - "project = \"wayoos-terraform-admin\""
          - "bucket = \"${branch.first}.tfstate.wayoos.info\""
    commands:
      init:
        - terraform init $HOME
        - terraform workspace new ${branch.last}
      up: [terraform apply]
      down: [terraform destroy -force]
  global:
    parent: terraform
    path: global
  bastion:
    parent: terraform
    path: mgmt/services/bastion
    environment:
      - OS_REGION_NAME2=EURCUSTOM
    commands:
      ssh: [./script-ssh-connect.sh]
  up:
    commands:
      all:
        - europe global up
        - USEast global up
        - bastion up
  down:
    commands:
      all: [bastion down]
