version: '1'
environments:
  europe:
    - OS_REGION_NAME=EUR
  USEast:
    - OS_REGION_NAME=US-EAST

services:
  global:
    path: global
    commands:
      init: [terraform init]
      up: ['terraform apply', 'terraform version']
      down: [terraform destroy]        
  bastion:
    path: mgmt/services/bastion
    environment:
      - OS_REGION_NAME2=EURCUSTOM
    commands:
      init: [terraform init]
      up: [terraform apply]
      down: [terraform destroy -force]
      ssh: [./script-ssh-connect.sh]

commands:
  init:
    - global init
    - bastion init
  up:
    - europe global up
    - USEast global up
    - bastion up
  down: [bastion down]
