version: '1'
datacenters:
  europe:
    environment:
      - OS_REGION_NAME=EUR
    services:
      global:
        path: global
        commands:
          init: [terraform init]
          up: ['terraform apply', 'terraform version']
          down: [terraform destroy]        
      bastion:
        path: mgmt/services/bastion
        commands:
          init: [terraform init]
          up: [terraform apply]
          down: [terraform destroy -force]
          ssh: [script-ssh-connect.sh]
  USEast:
    environment:
      - OS_REGION_NAME=US-EAST
    services:
      global:
        path: global
        commands:
          init: [terraform init]
          up: [terraform apply]
          down: [terraform destroy]        

commands:
  init:
    - europe global init
    - europe bastion init
  up:
    - europe global up
    - USEast global up
    - europe bastion up
  down: [europe bastion down]
